name: admin-ui-device
namespace: official
version: 1.1.1-2
author: Wazo Team
display_name: Devices
min_wazo_version: 18.03
tags:
  - internal
homepage: https://github.com/wazo-pbx/wazo-admin-ui-device
