name: admin-ui-device
namespace: official
version: 1.0.1-1
author: Wazo Team
display_name: Devices
min_wazo_version: 18.01
tags:
  - beta
  - internal
homepage: https://github.com/wazo-pbx/wazo-admin-ui-device
