name: admin-ui-device
namespace: official
version: 0.0.2
author: Wazo Team
display_name: Devices
min_wazo_version: 17.16
tags:
  - beta
  - internal
homepage: https://github.com/wazo-pbx/wazo-admin-ui-device
